### ISSUE TITLE
Stop requiring globally unique node ids

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1318]
We recently moved away from requiring globally unique node ids.
However, parts of our code still require it implicitly.
Because of that, we added checks to require it after all.

Tasks:
- [x] Make QGIS stop relying on `fid` for Node, #1306
- [x] Make QGIS stop relying on `fid` for Edge, #1310
- [x] Adapt optimization code to allow node ids that aren't globally unique #1262
- [ ] Adapt `to_xugrid`, https://github.com/Deltares/Ribasim/pull/1314#issuecomment-2019866629
- [ ] Revert https://github.com/Deltares/Ribasim/pull/1311
- [ ] Revert https://github.com/Deltares/Ribasim/pull/1316
- [x] Fix known bug in allocation: https://github.com/Deltares/Ribasim/pull/1330 
- [ ] Bring back tests: see what was reverted in https://github.com/Deltares/Ribasim/pull/1330/commits/d03526df8a4c62ce58edb7d67f13fd8ec6354dc1
- [ ] #1256

**Comment by Hofer-Julian** [comment]
Sounds like this can be (nearly?) closed

**Comment by visr** [comment]
I just unchecked some boxes, which were ticked since the related PRs were merged. But the task `revert #x` is not done when #x is merged.
