### ISSUE TITLE
Testmodels to represent automatic weir behaviour which fluctuates Q to keep H at a predefined level

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#262]
We need functionality to represent a very common situation in NL where an automatic were adjusts Q to keep H at a predefined level.

Preferably it is defined in an easy to use way, e.g. a specific type of connector node with some embedded control or a specific type of control node

Refinement 16/6/2023 Bart, Martijn, Peter

- [x] https://github.com/Deltares/Ribasim/issues/346
- [x]  https://github.com/Deltares/Ribasim/issues/347
- [x]  https://github.com/Deltares/Ribasim/issues/348
- [x]  https://github.com/Deltares/Ribasim/issues/323 (within the control layer a new PID-control is introduced, with as a first implementation only the P (proportional) part. In future his may be extended to PI and then PID. Links to https://github.com/Deltares/Ribasim/issues/322
- [x]  #300 make tests for usecases above

**Comment by gijsber** [comment]
Use case A: free flow situation with abundant upstream inflow
a fluctuating timeseries at a FlowBoundary, followed by 2 basins with a automatic weir inbetween. The weir has a target_waterlevel for the upstream basin as setpoint and a minimum and maximum waterlevel within which it should stay.
The Q_out is the controlled variable.

**Comment by gijsber** [comment]
Use case A.2: free flow situation with abundant upstream volume and level control on the downstream basin
a fluctuating timeseries at a FlowBoundary, followed by 2 basins with an automatic weir inbetween. The weir has a target_waterlevel for the downstream basin as setpoint and a minimum and maximum waterlevel within which it should stay. the downstream basin has a huge loss (evaporation or seepage) which needs to be compensated by inflow from the upstream basin.
The Q_in of the downstream basin (or the Q_out of the upstream basin) is the controlled variable.

**Comment by gijsber** [comment]
Use case A.3: free flow situation with limited upstream inflow and level control on both the upstream and the downstream basin
a fluctuating timeseries at a FlowBoundary, followed by 2 basins with an automatic weir inbetween. The weir has a target_waterlevel for the downstream basin as setpoint and a minimum and maximum waterlevel within which it should stay. The downstream basin has a huge loss (evaporation or seepage) which needs to be compensated by inflow from the upstream basin. The weir has a target_waterlevel for the upstream basin as setpoint and a minimum and maximum waterlevel within which it should stay.
Keeping the minimum water level at the upstream basin has priority over keeping the minimum water level at the downstream basin.
The inflow to the downstream basin is the controlled variable.

**Comment by gijsber** [comment]
Use case B.1: dual basin situation without inflow with a pump to control the water level of the upstream basin
The upstream basin has no upstream inflow, but has a target_waterlevel and a min/max water level, as well as an evaporation and infiltration loss that needs to be compensated. The water comes from the (huge) downstream basin storage and is brought upstream by a pump.

**Comment by gijsber** [comment]
Use case C.1 dual basin with limited inflow and a pump and an automatic weir to control the water level of the upstream basin.
the upstream basin has a target_waterlevel and a min/max water level, as well as an evaporation and infiltration loss.
In wintertime, the upstream inflow is sufficient to compensate the evaporation and infiltration loss, while the remaining water is discharged as a free flow sitation over the (automatic) weir to the downstream basin. 
In summertime, the upstream inflow is minimal and insufficient to compensate for the evaporation and infiltration loss. To preserve the minimal water level, the pump needs to be activated to bring water from the downstream basin to the upstream basin.

**Comment by gijsber** [comment]
Refinement 16/6/2023 Bart, Martijn, Peter
- [ ] Pump object is extended with min.flow capacity and max. pump capacity.  This provides the operating range to the controller. The pump is used to bring water from downstream (the lower level) to upstream (opposing gravity)
- [ ] A weir object is introduced in the physiscal layer with the same characteristics as the pump (min.capacity, max.capacity, static flow rate(s), transient flow rate, controllable flowrate), but an opposite flow direction (from upstream to downstream following gravity)
- [ ] Using the existing DiscreteController the static flow rate of the pump or the weir can be set
- [ ] within the control layer a new PID-control is introduced, with as a first implementation only the P (proportional) part. In future his may be extended to PI and then PID.

**Comment by SouthEndMusic** [comment]
> Use case A.1

This seems to be covered by the pump, as outflow from the controlled basin is required here.

**Comment by SouthEndMusic** [comment]
Regarding all these test models: 

- they cannot be implemented with (the current) PID control because PID control does not support min/max around a setpoint;
- The setpoint with min/max can be implemented with crossing aware truth states (https://github.com/Deltares/Ribasim/issues/447), but this is is dependent on https://github.com/Deltares/Ribasim/issues/487.
