### ISSUE TITLE
Metaissue: Ribasim-Modflow6 coupling

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#275]
- [x] Install ribasim_api locally from git (both)
- [x] Add ribasim_api git dependency to imod_coupler (Julian)
- [x] Add ribasim to pytest fixtures (Julian)
- [x] Add driver `ribamod` (Julian)
- [x] Create minimal, tailor-made MODFLOW6 and Ribasim model (Huite)
- [x] Couple MODFLOW6 and Ribasim (Huite)
- [ ] Document coupling: https://github.com/Deltares/Ribasim/issues/385
- [ ] Add interpolation for the volume to waterlevel table: https://github.com/Deltares/Ribasim/issues/284
- [ ] Create coupling tables with iMOD Python: https://github.com/Deltares/Ribasim/issues/285
- [ ] Allow exchange of multiple heads per basin (for multiple river/drainage systems): https://github.com/Deltares/Ribasim/issues/514
- [ ] Couple DFM nodes to MODFLOW boundaries #631
- [ ] Make debugging of Ribasim easier: https://github.com/Deltares/Ribasim/issues/286
- [ ] Release ribasim_api: https://github.com/Deltares/Ribasim/issues/287

**Comment by gijsber** [comment]
As discussed during meeting WS AA&MAAS (Joachim, Frank), WSL (Jurriaan), Deltares (Huite, Hendrik, Timo), WEnR (Ab), 22/9/2023
Topic: how to connect secundary and tertiary system and derived associated coupling data in hilly terrain

Assumption: a D-Hydro model is available for the primary system
D-Hydro provides QH-relations for the primary system as well the relation to translate the H or V from Ribasim to local H in the modflow river cells (H_mrc) as covered by the primary system/D-Hydro model. 

Proposal: use (at least) two Ribasim basins, one for the primary system, one for the secundary system
Conduct a DEM drainage analysis, supported with drainage areas afwaterings gebieden) or culvert information, to derive a routing of the secundairy system.
This network routing determines where the secondary system connects to the primary system.
At this connection point the head of the primary system is assumed similar to the head of teh seconadry system.
For the upstream branch of the secundary system one can assume either a horizontal water level (i.e. same h) or a waterlevel that follows the slope of the terrain.
In this way, the h-H relation can be derived

The volume relation for the secundary system can be derived from the DEM

To connect the basin representing the secundary system to the basin representing the primary system a QH-relation is derived using general characteristics of the secundairy system such as avg.profile, average length till the connection, representative Manning coefficient etc.

**Comment by Huite** [comment]
I suggest resolving the following three issues:

- [ ] #998
- [ ] #999

Then closing this meta-issue.

There will assuredly be many additional improvements (especially in terms of preprocessing robustness and the like), but they can be easily picked up piece by piece now.
