### ISSUE TITLE
Extrapolating the LinearInterpolation

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#279]
We use the LinearInterpolation from DataInterpolations for Q(h), A(S) and h(S) relations, the last two provided by users as A(h) once #225 is fixed.

It's important to control the extrapolation behavior, e.g. what happens if h is below the lowest h in the table, or above the largest. We currently have the default behavior of LinearInterpolation, which is linear based on the slope of the last segment. Visually:

![image](https://github.com/Deltares/Ribasim/assets/4471859/337e6c2d-9091-40c0-81d2-4c794aaf682b)

I think the linear extrapolation on the high end is fine, since generally the trend continues there, rather than stop. On the low end however we have a different situation, where we should keep it constant instead. So I think this is desired:

![image](https://github.com/Deltares/Ribasim/assets/4471859/af97147a-5d5a-4dcb-b6f2-77c1bce4802b)

There is no direct option for this in DataInterpolations, but it can be achieved by prepending an entry in the table, using `prevfloat` on the input, and the same output to get a horizontal segment.

**Q(h)**
- [x] First Q must be 0 #1469
- [x] If h is lower than minimum, keep it 0. #1469

**A(S) and h(S), provided by a user as A(h)**
- [x] First A must be >0. #438 undone in #472
- [x] Second A must be larger than 0. #438
- [x] If S is lower than 0, do constant extrapolation. In principle the solver should prevent S < 0, but good to do this for safety. This way the water level can't be below the bottom, and the area not below 0. Superseded by #1425.

The interpolation input, level, gets sorted. We currently don't enforce that the interpolation output, Q or A, are increasing (or staying constant). In most cases you want this, but it's possible to image scenarios where you don't. A bit contrived, but:

![image](https://github.com/Deltares/Ribasim/assets/4471859/22946159-cb5a-4419-b0d0-d6a61fee7387)

A decreasing surface water area is possible if you think about fishbowl or cave like profiles. And for Q(h) naturally this typically won't happen, but it could be of interest if you want to encode steering behavior without separate control rules.

- [x] Since it is quite rare, and in most cases a decreasing Q or A is a user error, I think we should start enforcing this. If there is a need for it in the future, we could add config options to enable decreasing Q or A, to allow the user to say, I know what I'm doing, don't get in my way.

- [x] For Q(h) a single row is probably fine, but for A(h) we need at least two, where the h is increasing, otherwise you cannot have storage.

**Comment by gijsber** [comment]
problem also experienced by @Fati-Mon
