### ISSUE TITLE
Placeholder issue for next steps control implementation

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#293]
## New features

Support more control listen variables:

-  ~~From basin: storage and area~~
- [x] From flow edges: flow (in `Control \ condition` turn `listen_node_id` in `listen_feature_id`) (#396)
- [ ] https://github.com/Deltares/Ribasim/issues/76
- ~~Forcing? Net change of basin?~~

Support more control affect nodes:

- [x] Give nodes other than pump also a `control_mapping` in the Julia core: `FractionalFlow`, ~~`LevelBoundary`~~, ~~`FlowBoundary`~~, `LinearResistance`, `ManningResistance`. For this also make a function like `parse_static` which handles having either controlled or uncontrolled nodes (when the `control_state` column is missing). Having time governed nodes should eventually also come in to this. Afterwords remove warnings in docs that only pump control is supported.
- [x] Supporting `TabulatedRatingCurve` probably takes some more individual effort. See #348
- ~~Basin profile? That would require special treatment since the profile is not specified in `Basin / static`.~~

Control output:

- [x] Create new output file in Julia core with record of what control did and when: https://github.com/Deltares/Ribasim/pull/303

Miscellaneous:

- [x] Make sure no fast oscillations occur between control states by setting minimal times for control states (time keeping already implemented): https://github.com/Deltares/Ribasim/issues/374
- [x] Rename Control to DiscreteControl to make the distinction with PID control clear: https://github.com/Deltares/Ribasim/issues/375

## QGIS plugin

- [x] Plot control and flow edges with different colors, maybe also plot (implicit) listen edges

## Documentation

- [x] Set up a more realistic example with control in `examples.ipynb`, e.g. the one used for the samenwerkingsdag presentation
- [x] Update addnode.qmd

## Validation

- [x] Add control graph validation (Julia) (#395)
- [x] #503
- [x] Add control logic validation (Python, Julia); e.g. the control nodes only come to control states which are defined for the nodes controlled by that control node, there is precisely one control state for every truth state.

## Tests

- [x] Add Julia tests on various control behaviours based on control output file

## Code refactoring

- [x] Python: `Edge.plot` kwarg handling, `Model.plot_control_listen` 
- [x] Possibly the schemas involving control, e.g. not having `truth_state` and `control_state` as strings. (other possibility: add wildcard option in truth state in stead of only true and false)

**Comment by evetion** [comment]
Based on PID control. We leave the preprocessing (such as deviation of net precipitation shortage) up to the user

- [ ] New condition based on time lookup with dT.

**Comment by gijsber** [comment]
I think we should consider basin-profile and boundary nodes as a given specification that can not/will not be controlled.
Also it is very unlikely (at the moment) that we want to control on volume or surface water area of the basin.
Volume control only may come into scope we ever need to include water accounting (ie reservoing water volumes for specific owners/users and managing that on a volume basis),
